---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/go-lint.yaml"
      - ".golangci.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/go-lint.yaml@7d23d5b64c0a3cdd65d931e59afc884d3d1da8fc
    secrets: inherit
    with:
      go-version: "1.22.5"
      golangci-version: "v1.60.3"
