---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Lint

on:
  workflow_dispatch: {}

  pull_request:
    paths:
      - ".github/workflows/go-lint.yaml"
      - ".golangci.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/go-lint.yaml@f59a3b8827b366707c1b6204e7f7613104e0d3d3
    secrets: inherit
    with:
      go-version: "1.22.5"
      golangci-version: "v1.60.3"
