---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Release

on:
  workflow_dispatch: {}

  push:
    tags: ["*"]

  pull_request:
    paths:
      - ".github/workflows/go-release.yaml"
      - ".goreleaser.yaml"
      - "go.mod"
      - "go.sum"
      - "cmd/**"

jobs:
  goreleaser:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@f59a3b8827b366707c1b6204e7f7613104e0d3d3
    secrets: inherit
    with:
      go-version: "1.22.5"
      goreleaser-version: "v2.2.0"
      dry-run: ${{ github.event.inputs.dry-run || github.event_name == 'pull_request' }}
      registry-url: "ghcr.io"
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GHCR_RW_TOKEN }}
