---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@f5355eac12d4835790fda578c36aa6741bf2fc87 # v3.4.17
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
