---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
