---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
