---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"

  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit

  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@f9e9b15c9203f390e79824a48408747deb7e89be # v3.4.12
    secrets: inherit
