---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"

  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit

  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@17c7b1454eb6e93d723a5fb2b55045d3fa767a80 # v3.4.16
    secrets: inherit
