---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@7d23d5b64c0a3cdd65d931e59afc884d3d1da8fc
    secrets: inherit
    with:
      config-file: ".github/configs/labeler.yaml"
