---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@main@779974ececd8243d133c1813f429e3415712456b
    secrets: inherit
    with:
      config-file: ".github/configs/labeler.yaml"
