---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/go-release.yaml@f59a3b8827b366707c1b6204e7f7613104e0d3d3
    secrets: inherit
    with:
      config-file: ".github/configs/labeler.yaml"
