---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: "false"
        required: false
      log-level:
        description: Log Level
        default: debug
        required: false
  schedule:
    - cron: "0 * * * *" # hourly

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: mirceanton/reusable-workflows/.github/workflows/renovate.yaml@update_workflows
    secrets: inherit
    with:
      dry-run: "${{ inputs.dry-run == true }}"
      log-level: "${{ inputs.log-level || 'debug' }}"
